site_name: Chelly Docs
repo_url: https://github.com/IgdaliasCabamba/chelly
edit_uri: edit/main/docs/

theme:
  
  name: "material"
  
  features:
    - header.autohide
    - announce.dismiss
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - toc.follow
    - toc.integrate 
    - search.suggest
    - search.highlight
    - search.share

  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/git-alt 

plugins:
  
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
  
  - git-revision-date-localized:
      enable_creation_date: true
  
  - git-committers:
      repository: IgdaliasCabamba/chelly
  
  - git-authors
  - search

nav:
  - Chelly Docs: index.md
  - tutorials.md
  - How-To Guides: how-to-guides.md
  - reference.md
  - explanation.md

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/dasgzmSU2e
      name: Icode server on Discord
  version:
    provider: mike
    default: stable


copyright: Copyright &copy; 2022 - 2022 Igdálias Cabamba
generator: false